// <auto-generated />
namespace VocabInstaller.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Review : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Review));
        
        string IMigrationMetadata.Id
        {
            get { return "201408250546457_Review"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
